
services:
  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
    ports:
      - 3306:3306
  
  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000